export const GAME_TYPE_VALUE_OPTIONS = [
  'Baccarat',
  'Bingo',
  'Blackjack',
  'Card Game',
  'Casino',
  'Dice',
  'Game Show',
  'Instant Win',
  'Keno',
  'Live Baccarat',
  'Live Bingo',
  'Live Blackjack',
  'Live Casino',
  'Live Dealer',
  'Live Dice',
  'Live Game Show',
  'Live Poker',
  'Live Roulette',
  'Live Slot',
  'Poker',
  'Roulette',
  'Scratchcards',
  'Slingo',
  'Slots',
  'Soft',
  'Solitaire',
  'Sports',
  'Table',
  'Video Poker',
  'Wheel'
];

export const SUB_GAME_TYPE_VALUE_OPTIONS = [
    'Live dealer',
    'Slingo',
    'Bingo',
    'Casino',
    'Live Casino',
    'Poker',
    'Scratchcards',
    'Slots',
    'Soft',
    'Video Poker',
    'Sports',
    'Instant Win',
    'Keno',
    'Table',
    'Auto Roulette',
    'Baccarat Variant',
    'BetOn Variant',
    'Bingo Game Show',
    'Limited Blackjack',
    'Live Talking Head Show',
    'Multiplier Baccarat',
    'Multiplier Dice',
    'Multiplier Roulette',
    'Multiplier Unlimited Blackjack',
    'Other Game Show',
    'Poker Variant',
    'Speed Roulette',
    'Standard Baccarat',
    'Standard Dice',
    'Standard Live Slot',
    'Standard Roulette',
    'Unlimited Blackjack',
    'Wheel Game show',
    "Dual Play Roulette",
];

export const FEDERAL_GAME_TYPE_VALUE_OPTIONS = [
    'Bingo',
    'Casino',
    'Poker',
    'Scratchcards',
    'Slots',
    'Soft',
    'Video Poker',
    'Sports',
    'Instant Win',
    'Keno',
    'Table',
];

export const CONTRACT_GAME_TYPE_VALUE_OPTIONS = [
    'Branded',
    'Standard',
    'Premium',
    'SSU',
    'Table/Scratchcard'
];

export const TAX_PRODUCT_TYPE_VALUE_OPTIONS = [
    'Table',
    'Slots',
    'Casino'
];

export const GAME_AGGREGATOR_VALUE_OPTIONS = [
  '1X2 Network',
  '3Radical',
  '4ThePlayer',
  'AGS',
  'Ainsworth',
  'Air Dice',
  'Amaya',
  'Amusnet',
  'Anaxi',
  'Arcadia',
  'Aristocrat',
  'Aristocrat Interactive',
  'Asia Gaming',
  'Aspect Gaming',
  'Authentic Gaming',
  'AvatarUX',
  'BF Games',
  'BetGames',
  'BetWorks',
  'Betsoft',
  'Big Time Gaming',
  'Bingo',
  'Blueprint',
  'Bombay Club',
  'Booming Games',
  'Booongo',
  'Bragg',
  'Colossus',
  'Concept Gaming',
  'DGC',
  'DFG',
  'Design Works Gaming',
  'DWG',
  'ELK Studios',
  'Electric Elephant',
  'Engage RGS',
  'Espresso Games',
  'Everi',
  'Evolution Gaming',
  'Evoplay',
  'Ezugi',
  'Eyecon',
  'Fantasma Games',
  'GAN',
  'GGLUS',
  'GameArt',
  'GameCode',
  'Gameplay Interactive',
  'Games Global',
  'Gamesys',
  'Gamesys Games',
  'Gamomat',
  'GameTech IOM',
  'Gamevy',
  'Gaming Corps',
  'Gaming Realms',
  'Genesis Gaming',
  'Greentube',
  'Hub88',
  'HungryBear',
  'IGT',
  'Incredible Technologies',
  'Inspired',
  'Jelly',
  'Kalamba Games',
  'Kiron Interactive',
  'Konami',
  'Leander Games',
  'Light & Wonder',
  'Lightning Box',
  'Lotus Live Gaming',
  'MPlay',
  'Manna Play',
  'Metric Gaming',
  'MicroGaming',
  'Mikado',
  'MultiSlot',
  'N2Live',
  'NetEnt',
  'NoLimit City',
  'Novomatic',
  'NYX',
  'ODDSworks',
  'OMI Gaming',
  'Octoplay',
  'Octopus Gaming',
  'OnAir Entertainment',
  'OneTouch',
  'Oryx Gaming',
  'Pariplay',
  'ParlayBay',
  'Play N Go',
  'Playgon',
  'Playson',
  'Playtech',
  'Playzido',
  'Pocket Games',
  'Poker',
  'PragmaticPlay',
  'Print Studios',
  'Push Gaming',
  'Quickfire',
  'Quickspin',
  'RAW',
  'RTG Asia',
  'RareStone',
  'Realistic Games',
  'Red Rake',
  'Red Tiger',
  'ReelPlay',
  'Reflex Gaming',
  'Reloaded Gaming',
  'Relax',
  'R3spin',
  'Ricochet',
  'Rogue',
  'Roxor Gaming',
  'S.Gaming',
  'SAGaming',
  'Sands',
  'Sapphire Gaming',
  'SDK',
  'SG Digital',
  'SGaming',
  'SGi',
  'SimplePlay',
  'Skywind',
  'Slingo Originals',
  'Slot Factory',
  'Slotmill',
  'SmartSoft',
  'Spin',
  'Spinomenal',
  'SportCaller',
  'Spribe',
  'Stakelogic',
  'Stakelogic V2 - STL',
  'Super Spade',
  'Thunderkick',
  'Tom Horn Gaming',
  'TopSpin',
  'Triple PG',
  'Vision RGS',
  'Vivo Gaming',
  'Wazdan',
  'WhiteHatStudios',
  'WMS',
  'Wizard Games',
  'Woohoo',
  'Xpress Gaming',
  'Yggdrasil'
];

export const GAME_PROVIDER_VALUE_OPTIONS = [
  '1X2 Network',
  '3Radical',
  '4ThePlayer',
  'AceRun',
  'AGS',
  'Ainsworth',
  'Air Dice',
  'Amaya',
  'Amusnet',
  'Anaxi',
  'Arcadia',
  'Aristocrat',
  'Aristocrat Interactive',
  'Asia Gaming',
  'Aspect Gaming',
  'Authentic Gaming',
  'AvatarUX',
  'Bang Bang',
  'BF Games',
  'BetGames',
  'Betsoft',
  'BetWorks',
  'Big Time Gaming',
  'Bingo',
  'Blueprint',
  'Bombay Club',
  'Booming Games',
  'Booongo',
  'Bragg',
  'Bulletproof',
  'Colossus',
  'Concept Gaming',
  'DGC',
  'DFG',
  'Design Works Gaming',
  'DWG',
  'ELK Studios',
  'Electric Elephant',
  'Engage RGS',
  'Espresso Games',
  'Everi',
  'Evolution Gaming',
  'Evoplay',
  'Ezugi',
  'Eyecon',
  'Fantasma Games',
  'G.Games',
  'GAN',
  'GGLUS',
  'GameArt',
  'GameCode',
  'Gameplay Interactive',
  'Games Global',
  'Gamesys',
  'Gamesys Games',
  'Gamomat',
  'GameTech IOM',
  'Gamevy',
  'Gaming Corps',
  'Gaming Realms',
  'Genesis Gaming',
  'Greentube',
  'Hub88',
  'HungryBear',
  'IGT',
  'Incredible Technologies',
  'Inspired',
  'Jelly',
  'Kalamba Games',
  'Kiron Interactive',
  'Konami',
  'Leander Games',
  'Light & Wonder',
  'Light & Wonder Spark',
  'Lightning Box',
  'Lotus Live Gaming',
  'MGA',
  'MPlay',
  'Manna Play',
  'Metric Gaming',
  'MicroGaming',
  'Mikado',
  'MultiSlot',
  'N2Live',
  'NetEnt',
  'NoLimit City',
  'Novomatic',
  'NYX',
  'ODDSworks',
  'OMI Gaming',
  'Octoplay',
  'Octopus Gaming',
  'OnAir Entertainment',
  'OneTouch',
  'Oryx Gaming',
  'Pariplay',
  'ParlayBay',
  'Peter & Sons',
  'Play N Go',
  'Playgon',
  'Playson',
  'Playtech',
  'Playzido',
  'Pocket Games',
  'Poker',
  'PragmaticPlay',
  'Print Studios',
  'Push Gaming',
  'Quickfire',
  'Quickspin',
  'R3spin',
  'RAW',
  'RareStone',
  'Realistic Games',
  'Red Rake',
  'Red Tiger',
  'Reflex Gaming',
  'Reloaded Gaming',
  'Relax',
  'ReelPlay',
  'Ricochet',
  'Rogue',
  'Roxor Gaming',
  'S.Gaming',
  'SAGaming',
  'Sands',
  'Sapphire Gaming',
  'SDK',
  'SG Digital',
  'SGaming',
  'SGi',
  'SimplePlay',
  'Skywind',
  'Slingo Originals',
  'Slot Factory',
  'Slotmill',
  'SmartSoft',
  'Spin',
  'Spinomenal',
  'SportCaller',
  'Spribe',
  'Stakelogic',
  'Stakelogic V2 - STL',
  'Super Spade',
  'Thunderkick',
  'Tom Horn Gaming',
  'TopSpin',
  'Triple PG',
  'Vision RGS',
  'Vivo Gaming',
  'Wazdan',
  'WhiteHatStudios',
  'WMS',
  'Wizard Games',
  'Woohoo',
  'Xpress Gaming',
  'Yggdrasil'
];

export const GAME_STUDIO_VALUE_OPTIONS = [
  '4ThePlayer',
  'AceRun',
  'Agatha Christie',
  'Alchemy Gaming',
  'All For One Studios',
  'All41 Studios',
  'Area Vegas',
  'AreaVegas Games',
  'Aristocrat',
  'Aristocrat Interactive',
  'Atlantic Digital',
  'Atomic Slot Lab',
  'Aurum Signature Studios',
  'AvatarUX',
  'Bally',
  'Baltic Studios',
  'Bang Bang',
  'Bang Bang Games',
  'Barcrest',
  'Barstruck',
  'Big Time Gaming',
  'Bluberi',
  'Blueprint',
  'Buck Stakes Entertainment',
  'Bulletproof',
  'Chance Interactive',
  'Circular Arrow',
  'Coin Machine Gaming',
  'Crazy Tooth Studio',
  'Crucible Gaming',
  'Daily Free Games',
  'Design Works Gaming',
  'DreamSpin',
  'DWG',
  'Elk Studios',
  'Endemol',
  'Everi',
  'Evolution Gaming',
  'Eyecon',
  'Foxium',
  'Fortune Factory Studios',
  'G.Games',
  'Gameburger Studios',
  'Gamomat',
  'Games Global',
  'Games Global (GGL)',
  'Games Global Portfolio',
  'Gamevy',
  'Gaming Arts',
  'Gaming Realms',
  'Gold Coin Studios',
  'Golden Hero',
  'Gong Gaming',
  'Greentube',
  'Hammertime Games',
  'Hasbro',
  'High Limit Studios',
  'Hungry Bear',
  'IGT',
  'Indigo Magic',
  'Infinity Dragon Studios',
  'INO Games',
  'Inspired Gaming',
  'Iron Dog',
  'Jelly',
  'Just For The Win Studios',
  'Just for the Win',
  'King Show Games',
  'Light & Wonder',
  'Lightning Box',
  'Lucksome Studios',
  'MGA',
  'MGM Group',
  'MicroGaming',
  'Nailed It Games',
  'Nailed It! Games',
  'Neko Games',
  'Neon Valley Studios',
  'NetEnt',
  'NextGen Gaming',
  'Northern Lights',
  'Northern Lights Gaming',
  'NYX',
  'Oros',
  'Oros Gaming',
  'Oryx',
  'Pariplay',
  'Pear Fiction Gaming',
  'PearFiction Studios',
  'Peter & Sons',
  'Play N Go',
  'Playtech',
  'Playzido',
  'Pragmatic Play',
  'PragmaticPlay',
  'Print Studios',
  'Pulse 8',
  'Push Actions',
  'Push Originals',
  'R3spin',
  'Raw',
  'Red 7',
  'Red Tiger',
  'Reel Hot Games',
  'Reflex Gaming',
  'Relax',
  'Ricochet',
  'Rogue',
  'Roxor Gaming',
  'S.Gaming',
  'Scientific Games',
  'Shufflemaster',
  'Side City',
  'Slingo',
  'Slingshot Studios',
  'Snowborn Games',
  'Spin Play Games',
  'Stakelogic',
  'Stormcraft Studios',
  'Switch Studios',
  'Triple Edge Studios',
  'Wazdan',
  'White Hat Studios',
  'Wishbone',
  'Wishbone Games',
  'WMS',
  'Yggdrasil'
];

export const REELS_VALUE_OPTIONS = [
  '3-3', '3-5', '4-5', '45721', '5', '5-3',
  '5-4', '5-5', '5-6', '6', '6-3', '6-4',
  '6-5', '6-6', '6-8', '7-6', '7-7', '8-8',
  '9-6', 'Crash', 'Megaways', 'Other', 'Tap'
];

export const WIN_LINES_VALUE_OPTIONS = [
  '1', '5', '9', '10', '11', '12',
  '13', '14', '15', '17', '20', '25',
  '30', '35', '40', '50', '60', '100',
  '50+', 'Other', 'ways'
];

export const WIN_LINE_TYPES_VALUE_OPTIONS = [
  'Bothways', 'Cluster', 'Cluster pays',
  'Crash', 'L2R', 'LrR',
  'Megaways', 'Other', 'Plinko',
  'scatter', 'Scatter pays', 'slingo',
  'Ways'
]
;

export const WAYS_TO_WIN_VALUE_OPTIONS = [
  '0', '5', '10', '20', '81',
  '125', '243', '250', '256', '432',
  '576', '720', '1024', '1200', '1296',
  '1875', '2304', '3072', '3125', '4096',
  '4608', '6400', '7776', '10000', '86436',
  '59049', '46656', '99225', '117649',
  '147456', '147649', '16807', '200704',
  '262144', '470596', '100000', '1000000', '*',
  '243 to 1024 in Wild Desire', '243 to 7776', 'Other'
];

export const SYMBOL_TYPES_VALUE_OPTIONS = [
    'Royals', 'Suits', 'BarX', 'Fruits', 'Gems',
    'Cash/Bullion', 'Other', 'Gold Bar', 'Bar', 'Gold', 'Fishing', 'Sevens', 'Sea'
];

export const THEMES_VALUE_OPTIONS = [
    'Action',
    'Adventure',
    'Africa',
    'America',
    'Americana',
    'Ancient Civilizations',
    'Animals',
    'Ape',
    'Arabian',
    'Arabic',
    'Asian',
    'Atlantis',
    'BESPOKE',
    'Bank',
    'Birds',
    'Bison/Buffalo',
    'Branded',
    'Bubble',
    'Candy/Sweets',
    'Cats',
    'Carnival',
    'Chinese',
    'Christmas',
    'Classic',
    'Retro',
    'Crime',
    'Detective',
    'Devil',
    'Dinosaurs',
    'Dragon',
    'Drums',
    'Egypt',
    'Egyptian',
    'Elements',
    'Espionage',
    'Fairy Tale',
    'Fantasy',
    'Farm',
    'Fire',
    'Fishing',
    'Fruit',
    'Gangsters',
    'Gems',
    'Genie',
    'Gods',
    'Gold',
    'Greece',
    'Halloween',
    'Horror',
    'Irish',
    'Island',
    'Historic',
    'Joker',
    'Jungle',
    'King',
    'Latin American Ancient Civilisations',
    'Licensed',
    'Luxury',
    'Magic',
    'Magic/Alchemy',
    'Masks',
    'Mayan/Aztec',
    'Aztec',
    'Medieval',
    'Mexico',
    'Mining',
    'Mining/Prospector',
    'Money',
    'Moon',
    'Music',
    'Mythology',
    'Nature',
    'No Theme',
    'Other',
    'Oz',
    'Pets',
    'Pig',
    'Piggy',
    'Pirate',
    'Poultry',
    'Prehistoric',
    'Robbery',
    'Roman',
    'Romance/Love',
    'Rome',
    'Royal',
    'Sevens',
    'Space',
    'Sports',
    'Steampunk',
    'Sweets',
    'Tiki',
    'Tomb Raider',
    'Train',
    'Tropical',
    'Underwater',
    'Urban',
    'Vampires',
    'Vegas',
    'Casino/Vegas',
    'Vikings',
    'Vikings/Norse',
    'Volcano',
    'Water',
    'Western',
    'Wild West',
    'Winter',
    'Wolf',
    'Xmas'
];

export const FEATURES_VALUE_OPTIONS = [
    '0',
    '3 reel slot mechanic',
    'Added Wilds',
    'Advance Symbols',
    'Alpha Respins',
    'Alpha Super Bonus',
    'Ante Bet',
    'Any Adjacent Pays',
    'Bi-directional Pays',
    'Bidirectional pays',
    'Boom Brothers Feature',
    'Book feature',
    'Bonus Boost',
    'Bonus Buy',
    'Bonus Game',
    'Bonus Pick Game',
    'Bonus Prize Tsunami',
    'Bonus Recharge',
    'Bonus wheel',
    'Buy Bonu',
    'Buy Bonus',
    'Buy Feature',
    'Buy a Bonus',
    'Card Gamble',
    'Card Gamble Feature',
    'Cash Collect',
    'Cash Collectopm',
    'Cash Collection',
    'Cash Eruption',
    'Cash Pots',
    'Cash Respin',
    'Cascading Reels',
    'Cascading Symbols',
    'Cascading Wins',
    'Collosal Symbolsm Stacked Wilds',
    'Colossal Symbols',
    'Collect and Collect & Respin Feature',
    'Collection Pot',
    'Countdown Clock',
    'Crazy Cart Wilds',
    'Crash',
    'Epanding Wild',
    'Epic Strike',
    'Expanding Reels',
    'Expanding Symbols',
    'Expanding Wilds',
    'Extra Spins',
    'Feature Gamble',
    'Fixed Jackpot',
    'Fixed Jackpots',
    'Flaming Link Feature',
    'Fortune Bet',
    'Fortune Bet Feature',
    'Fortune Play',
    'Free Games',
    'Free Games Feature',
    'Free Rounds',
    'Free Spin Feature',
    'Free Spins',
    'Free Spins Pick',
    'Gift Box Feature',
    'Gift of the Great Bear Feature',
    'Gold & Win',
    'Gold Carts',
    'Golden Bass Respins',
    'Golden Bass Respins Special Features',
    'Golden Bass Wilds',
    'Golden Fish Basket',
    'Golden Free Spins',
    'Golden Respins',
    'Great Bear Bonus.',
    'Great Bear Multiplier Feature',
    'Growing Jackpots / Modifiers',
    'Guaranteed Gift Box Feature',
    'Guaranteed Symbols',
    'Guaranteed Wins',
    'Gamble',
    'Gamble Wheel',
    'HyperSpins',
    'Increasing / Varying Pay Ways',
    'Increasing/Varying payways',
    'Instant Prize',
    'Jackpot Game',
    'Jackpots',
    'Joker',
    'Jumbo Symbols',
    'Ladder Bonus',
    'Ladder Feature',
    'Link & Win',
    'Link & Win Extended',
    'Link & Win Modifiers',
    'Lock & Collect',
    'Lock and Win',
    'Megaways',
    'Midas Collection',
    'Match to Win',
    'Modifiers',
    'Money Scatter',
    'Money Spins',
    'Multi Chase',
    'Multi Feature',
    'Multi-Grid',
    'Multi-grid',
    'Multiplier Symbols',
    'Multipler with or without Wilds',
    'Multipliers',
    'Multipliers (With or without wilds)',
    'Multipliers with Ot without Wilds',
    'Multiple Entry Points for Bonus',
    'Mystery Symbol',
    'Mystery Symbol Scatter Symbol',
    'Mystery Symbols',
    'No Feature',
    'Nudge Feature',
    'Nudging Symbols',
    'Other Monetisation',
    'Other Wilds',
    'Paid Feature',
    'Pay Anywhere',
    'Pick Feature',
    'Pick Me',
    'Pick a Prize',
    'Player Choice',
    'Plinko',
    'Pot Collection',
    'Power Combo',
    'Pre-Bonus Game for Modifiers',
    'Prize Ladded',
    'Prize Ladder',
    'Prize Wheel',
    'Quack Shot',
    'Random Wilds',
    'Random Win Creation',
    'Replicating Reels',
    'Respin',
    'Respin with an Eel',
    'Returning Symbols',
    'Reveal to win bonus',
    'Rewind',
    'Risk Ladder Gamble',
    'Risk Ladder Gamble Feature',
    'Rolling Reels',
    'Scatters',
    'Scatter Symbols',
    'Scatter Wilds/Symbols',
    "Shark's Lock Bonus Prizes",
    'Spin Chance',
    'Spreading Wilds',
    'Stacked Symbols',
    'Stacked Wilds',
    'Static Jackpot',
    'Static Jackpots',
    'Statis Jackpot',
    'Statis Jackpots',
    'Status Jackpot',
    'Sticky Stacked Wild Symbol',
    'Sticky Symbols',
    'Sticky Wilds',
    'Super Collect',
    'Super Free Spins',
    'Super Joker',
    'Super Spin',
    'Super Spins',
    'Symbol Climb Feature',
    'Symbol Upgrade',
    'Synced Reels',
    'Token/Reel Collection',
    'Trail',
    'Trail Bonus',
    'Trail Cascading Reels',
    'Trail Feature',
    'Unlockable Features',
    'Unlockable Modifiers',
    'Upgrades',
    'Upgrading Feature',
    'Upgrading Symbols',
    'Upsizer',
    'Walking Symbols',
    'Wheel',
    'Wheel Bonus',
    'Wheel Feature',
    'Wild Jokers',
    'Wild Link',
    'Wild Links',
    'Wild Power Spins',
    'Wild Reels',
    'Wild Scrolls',
    'Wild Symbol',
    'Wild Symbols',
    'Wilds',
    'Wilds with Ot without Multipliers',
    'Wilds with or without Multiplie',
    'Wilds with or without Multiplies',
    'Wilds with or without Multiplier',
    'Wilds with or without Multipliers',
    'Win Stepper Collect',
    'XUP'
];

export const BRANDS_VALUE_OPTIONS = [
    "Bally's",
    "Britains Got Talent",
    "Charlie and the Chocolate Factory",
    "Deal or no deal",
    "Dumb and Dumber",
    "Lara Croft",
    "Maradona",
    "Monopoly",
    "No",
    "Press Your Luck",
    "Rambo",
    "Rick and Morty",
    "Space Invaders",
    "Squid Game",
    "Stargate",
    "Terminator",
    "Tetris",
    "The Flintstones",
    "The Godfather",
    "The Goonies",
    "The Lost Boys",
    "The Phantom of the Opera",
    "Top Cat",
    "Virgin",
    "Virgin Games",
    "Who Wants To Be A Millionaire",
    "Worms",
    "Yes"
];
