export const SYMBOL_TYPES_MAP = {
    Royals: 'Royals',
    Suits: 'Suits',
    Other: 'Other',
    'Gold Bar': 'Gold Bar',
    Fruits: 'Fruits',
    Fruit: 'Fruits',
    Gems: 'Gems',
    'Cash / Bullion': 'Cash / Bullion',
};

export const FEATURES_MAP = {
    'Free Spins': 'Free Spins',
    'free Spins': 'Free Spins',
    'Free spins': 'Free Spins',
    'Boost Mode': 'Boost Mode',
    'Boost mode': 'Boost Mode',
    'Link & Win': 'Link & Win',
    'Link&Win': 'Link & Win',
    'Link & Win Modifiers': 'Link & Win Modifiers',
    'Link&Win Modifiers': 'Link & Win Modifiers',
    'Link & Win Extended': 'Link & Win Extended',
    'Growing Jackpots / Modifiers': 'Growing Jackpots / Modifiers',
    'Growing jackots/modifiers': 'Growing Jackpots / Modifiers',
    'Boost Feature': 'Boost Feature',
    'Buy a bonus': 'Buy a bonus',
    'Buy a Bonus': 'Buy a bonus',
    'Expanding Wilds': 'Expanding Wilds',
    'Stacked Wilds': 'Stacked Wilds',
    'Sticky Wilds': 'Sticky Wilds',
    'Other Wilds': 'Other Wilds',
    'Mystery Symbols': 'Mystery Symbols',
    'Respins': 'Respins',
    'Multipliers (With or without wilds)': 'Multipliers (With or without wilds)',
    'Bonus Game': 'Bonus Game',
    'Gamble': 'Gamble',
    'Hold and Win': 'Hold and Win',
    'Trail': 'Trail',
    'Cascading Reels': 'Cascading Reels',
    'Pick Me': 'Pick Me',
    'Cash Collect': 'Cash Collect',
    'Feature Gamble': 'Feature Gamble',
    'Expanding Reels': 'Expanding Reels',
    'Expanding Symbols': 'Expanding Symbols',
    'Random Wilds': 'Random Wilds',
    'Stacked Symbols': 'Stacked Symbols',
    'Sticky Symbols': 'Sticky Symbols',
    'Super Free Spins': 'Super Free Spins',
    'Symbol Upgrade': 'Symbol Upgrade',
    'Rolling Reels': 'Rolling Reels',
    'Wheel': 'Wheel',
    'Wilds': 'Wilds',
    'Wild Link': 'Wild Link',
    'Wild Reel(s)': 'Wild Reel(s)',
    'Wild Scrolls': 'Wild Scrolls',
    'Synced Reels': 'Synced Reels',
    'Unlockable Modifiers': 'Unlockable Modifiers',
    'Walking Symbols': 'Walking Symbols',
    'Crash': 'Crash',
    'Plinko': 'Plinko',
    'Megaways': 'Megaways',
    'Pick Feature': 'Pick Feature',
    'Match to Win': 'Match to Win',
    'Scatter Symbols': 'Scatter Symbols',
    'Trail Feature': 'Trail Feature',
    'Jumbo Symbols': 'Jumbo Symbols',
    'Token/Reel Collection': 'Token/Reel Collection',
    'Respin': 'Respin',
    'Stacked Jackpots': 'Stacked Jackpots',
    'Static Jackpot': 'Static Jackpot',
    'Static Jackpots': 'Static Jackpots',
    'Power Combo': 'Power Combo',
    'Pre-Bonus Game for Modifiers': 'Pre-Bonus Game for Modifiers',
    'Ladder Bonus': 'Ladder Bonus',
    'Bonus wheel': 'Bonus wheel',
    'Book feature': 'Book feature',
    'Bonus Recharge': 'Bonus Recharge',
    'Buy Feature': 'Buy Feature',
    'Buy feature': 'Buy Feature',
    'HyperSpins': 'HyperSpins',
    'Fortune Bet Feature': 'Fortune Bet Feature',
    'Fortune Play': 'Fortune Play',
    'Multi Feature': 'Multi Feature',
    'Multi-Grid': 'Multi-Grid',
    'Multi-grid': 'Multi-grid',
    'Multiple Entry Points for Bonus': 'Multiple Entry Points for Bonus',
    'Multipliers': 'Multipliers',
    'No Feature': 'No Feature',
    'Nudging Symbols': 'Nudging Symbols',
    'Other Monetisation': 'Other Monetisation',
    'Paid Feature': 'Paid Feature',
    'Pay Anywhere': 'Pay Anywhere',
    'Player Choice': 'Player Choice',
    'Random Win Creation': 'Random Win Creation',
    'Returning Symbols': 'Returning Symbols',
    'Reveal to win bonus': 'Reveal to win bonus',
    'Scatter Wilds/Symbols': 'Scatter Wilds/Symbols',
    'Spin Chance': 'Spin Chance',
    'Spreading Wilds': 'Spreading Wilds',
    'XUP': 'XUP'
};

export const THEMES_MAP = {
    'Nature': 'Nature',
    'Magic': 'Magic',
    'Branded': 'Branded',
    'Fruit': 'Fruit',
    'Fruits': 'Fruit',
    'Egypt': 'Egypt',
    'Egyptian': 'Egyptian',
    'Gems': 'Gems',
    'Gems.1': 'Gems',
    'Gems/Diamonds': 'Gems',
    'Irish': 'Irish',
    'Fishing': 'Fishing',
    'Other': 'Other',
    'Other.1': 'Other',
    'Water': 'Water',
    'Asian': 'Asian',
    'Money': 'Money',
    'Jungle': 'Jungle',
    'Christmas': 'Christmas',
    'Mining': 'Mining',
    'Mining/Prospector': 'Mining',
    'Fairy Tale': 'Fairy Tale',
    'Fairytale': 'Fairy Tale',
    'Wild West': 'Wild West',
    'Fantasy': 'Fantasy',
    'Mayan/Aztec': 'Mayan/Aztec',
    'Mexican': 'Mexico',
    'Mexico': 'Mexico',
    'Space': 'Space',
    'Pirate': 'Pirate',
    'Pirates': 'Pirate',
    'Winter': 'Winter',
    'Detective': 'Detective',
    'Dinosaurs': 'Dinosaurs',
    'Vikings': 'Vikings',
    'Vikings/Norse': 'Vikings',
    'Farm': 'Farm',
    'Sweets': 'Sweets',
    'Candy/Sweets': 'Sweets',
    'Bubble': 'Bubble',
    'Sports': 'Sports',
    'Tomb Raider': 'Tomb Raider',
    'Retro': 'Retro',
    'Classic': 'Classic',
    'Elements': 'Elements',
    'Medieval': 'Medieval',
    'Gods': 'Gods',
    'Fire': 'Fire',
    'Horror': 'Horror',
    'Bank': 'Bank',
    'Robbery': 'Robbery',
    'Greece': 'Greece',
    'Island': 'Island',
    'Atlantis': 'Atlantis',
    'Music': 'Music',
    'Arabic': 'Arabic',
    'Arabian': 'Arabic',
    'Rome': 'Rome'
};
